apiVersion: v1
kind: ConfigMap
metadata:
  name: gost-config
  namespace: gost2warp
data:
  gost.yaml: |
    services:
      - name: "socks-proxy"
        addr: ":1080"
        handler:
          type: auto
          retries: 2
          auther: socks-auther
          chain: warp-chain
        listener:
          type: tcp

    authers:
      - name: socks-auther
        reload: 10s
        file:
          path: /tmp/gost_socks_auth

    chains:
      - name: warp-chain
        selector:
          strategy: rand
          maxFails: 1
          failTimeout: 30s
        hops:
          - name: warp-hop
            nodes:
              - name: warp1
                addr: warp1:1080
                connector:
                  type: socks5
                dialer:
                  type: tcp
              - name: warp2
                addr: warp2:1080
                connector:
                  type: socks5
                dialer:
                  type: tcp
              - name: warp3
                addr: warp3:1080
                connector:
                  type: socks5
                dialer:
                  type: tcp
