apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gost2warp
resources:
  - namespace.yaml
  - gost-config.configmap.yaml
  - warp.workloads.yaml
  - gost.workloads.yaml
  - rotator-rbac.yaml
  - rotator-cronjobs.yaml
